### PR TITLE
fix build issues for oneAPI beta10

### PR DESCRIPTION
**Pull request by abagusetty**

### CODE REVIEW

**Comment by wavefunction91** [comment]
@abagusetty Does this have backwards compatibility, or does it bump the DPC++ requirement to a newer version?

**Comment by abagusetty** [comment]
> @abagusetty Does this have backwards compatibility, or does it bump the DPC++ requirement to a newer version?

It looks like they are bumping the requirements since everything is under beta releases. Also, I'll convert this PR to WIP, just to put in non-batched GEMM such that it can be packed together.

**Comment by wavefunction91** [comment]
@abagusetty Is this good-to-go?

**Comment by abagusetty** [comment]
> @abagusetty Is this good-to-go?

Yes, it should be good for merge

**Pull request merged**
